highlighter: rouge
gems: 
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-seo-tag
encoding: utf-8
paginate: 8
paginate_path: "page:num"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge


permalink: /:year/:month/:day/:title/
  

name: Yan
bio: Nothing is true
logo: "/logo.png"
email: hang.yan@hotmail.com
fav: "/assets/img/fav/favicon.png"

collections:
  microblog:
    output: true
    permalink: microblog/:year/:month/:title/


defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_ad: true

navs:
  - 
    href: /
    label: 首页
  - 
    href: /microblog/
    label: 微博
  - 
    href: /articles/
    label: 目录
  -
    href: /feed/
    label: 订阅
  - 
    href: /about/
    label: 关于
    
# ---------------- #
#      Socials     #
# ---------------- #
github_id: hangyan
douban_id: yanhangyhy
steam_id: yayu49

