highlighter: rouge
gems: [jekyll-paginate]
encoding: utf-8
paginate: 8
paginate_path: "page:num"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

name: Alex的Notebook
bio: 雄关漫道真如铁，而今迈步从头越
logo: "/img/sin.jpg"
# url: http://jaeger.itscoder.com/
email: qqliao_shu_feng@163.com
fav: "/assets/img/fav/favicon.ico"

defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_ad: true

navs:
  - 
    href: /
    label: 首页
  - 
    href: /articles/
    label: 目录
  -
    href: /feed/
    label: 订阅
  - 
    href: /about/
    label: 关于

# ---------------- #
#      Socials     #
# ---------------- #
github_id: alexknight
weibo_id: 6518850128
zhihu_id: alexknight
blog_id: alexkn