highlighter: rouge
gems: [jekyll-paginate]
encoding: utf-8
paginate: 8
paginate_path: "page:num"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

name: Blog
bio: Nothing is true
logo: "/images/sin.jpg"
email: hang.yan@hotmail.com
fav: "/assets/img/fav/favicon.ico"

defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_ad: true

navs:
  - 
    href: /
    label: 首页
  - 
    href: /articles/
    label: 目录
  -
    href: /feed/
    label: 订阅
  - 
    href: /about/
    label: 关于

# ---------------- #
#      Socials     #
# ---------------- #
github_id: hangyan